print("\u2620 skull")
print("\u25A1 blank")
print("\u1F33 snake")
print("\u4DEF castle")
print("\u0D9E amongus")
print("Д Legs?")
print("¹ ² ³ ¤ € ’ ¥ × ä å é ë þ ü ú í ó ö « » ¬ á ß ð f g h ï œ ø ¶ ǽ œ © ® ® b ñ µ ç ¿ uncapped EXTD")
print("¡ ˝ ¯ £ ¸ ¼ ½ ¾ ˘ ° Ä Å É Ë Þ Ü Ú Í Ó Ö “ ” ¦ ¨ ° Ø Œ Ï H G F Ð § Á Æ Œ ¢ ® ® B B Ñ µ Ç capped EXTD")
print("A // B || C :: D <> E ## F ** G )( H ^^ I ++ J == K -- L ǂǂ M ǁ N ʬ O ʭ P Ξ Q ж R н S ֍ T ٭ U ۞ V ܀ W ܍ X ౼ Y ෴ Z ග A  B  C")
print("telegu for enemies like ౡ")